input {
  beats_pqc {
    port => 5044
    host => "0.0.0.0"

    ssl_certificate => "/usr/share/logstash/certs/elasticsearch/elasticsearch.crt"
    ssl_key => "/usr/share/logstash/certs/elasticsearch/elasticsearch.key"
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
    ssl_client_authentication => "none"

    pqc_enabled => true
    pqc_hybrid_group => "X25519MLKEM768"
    pqc_require => true
    pqc_allow_fallback => false
    pqc_debug_handshake => true
  }
}

output {
  stdout { codec => rubydebug }
}
